---
- name: Create directories for {{ app_name }} port patch
  ansible.builtin.include_tasks: changeCommon.yml

- name: Create {{ app_name }} patch-port script
  ansible.builtin.template:
    src: patch-port.sh.j2
    dest: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/{{ app_name }}/config/patch-port.sh"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"

- name: Add cron for {{ app_name }} patch-port
  ansible.builtin.lineinfile:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/{{ app_name }}/crontabs/root"
    line: "@reboot /config/patch-port.sh"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
