---
- name: Check if {{ app_name }} config file exists
  ansible.builtin.stat:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/{{ app_name }}/config/config.xml"
  register: seedbox_config_file_stat
  tags: seedbox

- name: Load {{ app_name }} Config File
  ansible.builtin.slurp:
    src: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/{{ app_name }}/config/config.xml"
  register: seedbox_app_config
  when: seedbox_config_file_stat.stat.exists
  tags: seedbox

- name: Get {{ app_name }} API Key
  ansible.builtin.set_fact:
    "seedbox_{{app_name}}_api_key": "{{ seedbox_app_config.content | b64decode | regex_search('<ApiKey>(.*?)</ApiKey>', '\\1') }}"
  when: seedbox_config_file_stat.stat.exists
  tags: seedbox
