---
- name: Create symlinks for media shares
  file:
    src: "/mnt/{{ unraid_mount_tag }}/{{ item.sharePath }}"
    dest: "/data/{{ item.mediaType }}"
    state: link
  loop: "{{ media_shares }}"
  tags:
    - seedbox

- name: Create links directory for media shares
  file:
    path: "/links"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0755
  tags:
    - seedbox

- name: Create torrent download link
  file:
    src: "/data/downloads/Torrents"
    dest: "/links/Torrents"
    state: link
  tags:
    - seedbox

- name: Create usenet download link
  file:
    src: "/data/downloads/Usenet"
    dest: "/links/Usenet"
    state: link
  tags:
    - seedbox

- name: Create dockers directory for seedbox stack
  file:
    path: "/home/{{ docker_user }}/dockers/seedbox"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0755
  tags:
    - seedbox

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ docker_user }}/dockers/seedbox/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0644
  tags:
    - seedbox

- name: Create .env
  template:
    src: .env.j2
    dest: "/home/{{ docker_user }}/dockers/seedbox/.env"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0644
  tags:
    - seedbox

- name: Create Seedbox Docker stack
  command:
    cmd: "docker compose -f /home/{{ docker_user }}/dockers/seedbox/docker-compose.yml up -d"
  tags:
    - seedbox

