---
- name: Create dockers directory for seedbox stack
  file:
    path: "/home/{{ docker_user }}/dockers/seedbox"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - seedbox

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ docker_user }}/dockers/seedbox/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0644"
  tags:
    - seedbox

- name: Create Seedbox Docker stack
  command:
    cmd: "docker compose -f /home/{{ docker_user }}/dockers/seedbox/docker-compose.yml up -d"
  tags:
    - seedbox
