---
- name: Ensure the /data directory exists
  file:
    path: /data
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present
  tags:
    - seedbox

- name: Initialize nfs_media_shares as an empty list
  set_fact:
    nfs_media_shares: []

- name: Resolve NFS media shares paths
  set_fact:
    nfs_media_shares: "{{ nfs_media_shares + [ item | combine({'nfs_path': nfs.base_path + '/' + item.nfs_path}) ] }}"
  with_items: "{{ nfs.media_shares }}"


- name: Mount NFS shares
  mount:
    path: "/data/{{ item.data_dir_name }}"
    src: "{{ nfs.host }}:{{ item.nfs_path }}"
    fstype: nfs
    opts: "rw,sync"
    state: mounted
  loop: "{{ nfs_media_shares }}"
  tags:
    - seedbox

- name: Create dockers directory for seedbox stack
  file:
    path: "/home/{{ docker_user }}/dockers/seedbox"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - seedbox

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ docker_user }}/dockers/seedbox/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0644"
  tags:
    - seedbox

- name: Create .env
  template:
    src: .env.j2
    dest: "/home/{{ docker_user }}/dockers/seedbox/.env"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0644"
  tags:
    - seedbox

- name: Create Seedbox Docker stack
  command:
    cmd: "docker compose -f /home/{{ docker_user }}/dockers/seedbox/docker-compose.yml up -d"
  tags:
    - seedbox

