---
- name: Create dockers directory for seedbox stack
  ansible.builtin.file:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - seedbox

- name: Check for Radarr name change
  ansible.builtin.set_fact:
    radarr_name_change: "{{ containers.radarr and radarr.instance_name is defined }}"
  tags: seedbox

- name: Check for Radarr 2 name change
  ansible.builtin.set_fact:
    radarr_2_name_change: "{{ containers.radarr_2 and radarr_2.instance_name is defined }}"
  tags: seedbox

- name: Check for Sonarr name change
  ansible.builtin.set_fact:
    sonarr_name_change: "{{ containers.sonarr and sonarr.instance_name is defined }}"
  tags: seedbox

- name: Check for Sonarr 2 name change
  ansible.builtin.set_fact:
    sonarr_2_name_change: "{{ containers.sonarr_2 and sonarr_2.instance_name is defined }}"
  tags: seedbox

- name: Check for Readarr Audiobooks name change
  ansible.builtin.set_fact:
    readarr_audiobooks_name_change: "{{ containers.readarr_audiobooks and readarr_audiobooks.instance_name is defined }}"
  tags: seedbox

- name: Check for Readarr Ebooks name change
  ansible.builtin.set_fact:
    readarr_ebooks_name_change: "{{ containers.readarr_ebooks and readarr_ebooks.instance_name is defined }}"
  tags: seedbox

- name: Change Radarr Instance name
  when: radarr_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "radarr"
    target_name: "{{ radarr.instance_name }}"
    default_name: "Radarr"

- name: Change Radarr 2 Instance name
  when: radarr_2_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "radarr_2"
    target_name: "{{ radarr_2.instance_name }}"
    default_name: "Radarr"

- name: Change Sonarr Instance name
  when: sonarr_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "sonarr"
    target_name: "{{ sonarr.instance_name }}"
    default_name: "Sonarr"

- name: Change Sonarr 2 Instance name
  when: sonarr_2_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "sonarr_2"
    target_name: "{{ sonarr_2.instance_name }}"
    default_name: "Sonarr"

- name: Change Readarr Audiobooks Instance name
  when: readarr_audiobooks_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "readarr_audiobooks"
    target_name: "{{ readarr_audiobooks.instance_name }}"
    default_name: "Readarr"

- name: Change Readarr Ebooks Instance name
  when: readarr_ebooks_name_change
  tags: seedbox
  ansible.builtin.include_tasks: changeName.yml
  vars:
    app_name: "readarr_ebooks"
    target_name: "{{ readarr_ebooks.instance_name }}"
    default_name: "Readarr"

- name: Change radarr 2 port
  when: containers.radarr_2 and containers.pia_vpn
  tags: seedbox
  ansible.builtin.include_tasks: changePort.yml
  vars:
    app_name: "radarr_2"
    target_port: "{{ seedbox_radarr_2_internal_port }}"

- name: Change sonarr 2 port
  when: containers.sonarr_2 and containers.pia_vpn
  tags: seedbox
  ansible.builtin.include_tasks: changePort.yml
  vars:
    app_name: "sonarr_2"
    target_port: "{{ seedbox_sonarr_2_internal_port }}"

- name: Change readarr ebooks port
  when: containers.readarr_ebooks and containers.pia_vpn
  tags: seedbox
  ansible.builtin.include_tasks: changePort.yml
  vars:
    app_name: "readarr_ebooks"
    target_port: "{{ seedbox_readarr_ebooks_internal_port }}"

- name: Check if the pia port.dat file is in root pia directory (Migration step)
  ansible.builtin.stat:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/port.dat"
  register: pia_port
  tags:
    - seedbox
  when: containers.pia_vpn

- name: Create new pia port directory if neeeded (Migration step)
  ansible.builtin.file:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/port"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
    recurse: true
  tags:
    - seedbox
  when: containers.pia_vpn and pia_port.stat.exists

- name: Move pia port.dat file to new location (Migration step)
  ansible.builtin.command:
    cmd: >
      mv /home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/port.dat
      /home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/port/port.dat
    creates: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/port/port.dat"
  tags:
    - seedbox
  when: containers.pia_vpn and pia_port.stat.exists

- name: Copy mam.sh to persist directory (Extras MAM)
  ansible.builtin.copy:
    src: mam.sh
    dest: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/persist/mam.sh"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - seedbox
  when: extras.mam.enabled and containers.pia_vpn

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0644"
  tags:
    - seedbox

- name: Create mam pia directory
  ansible.builtin.file:
    path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/persist"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"

- name: Setup Cleanuperr Ignored file
  when: containers.cleanuparr and cleanuparr.queue_cleaner.enabled and cleanuparr.ignored is defined
  tags: seedbox
  block:
    - name: Create dockers directory for seedbox stack
      ansible.builtin.file:
        path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/cleanuparr"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0755"

    - name: Create/Wipe Cleanuperr Ignored file
      ansible.builtin.copy:
        content: ""
        dest: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/cleanuparr/ignored.txt"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0755"
        backup: true

    - name: Add lines to Cleanuperr Ignored file
      ansible.builtin.lineinfile:
        path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/cleanuparr/ignored.txt"
        line: "{{ item }}"
      loop: "{{  cleanuparr.ignored }}"

- name: Create Seedbox Docker stack
  ansible.builtin.command:
    cmd: "docker compose -f /home/{{ docker_user }}/dockers/{{ docker_directory_name }}/docker-compose.yml up -d"
  changed_when: true
  tags:
    - seedbox

# We dont need to restart sonarr_2 or radarr_2 because they will be restarted by the healthcheck
- name: Restart containers that have a name change
  tags:
    - seedbox
  when: radarr_name_change or sonarr_name_change or readarr_audiobooks_name_change or readarr_ebooks_name_change
  block:
    - name: Wait for 30 seconds to allow the containers to start
      ansible.builtin.pause:
        seconds: 30

    - name: Restart Radarr container
      ansible.builtin.command:
        cmd: "docker restart radarr"
      when: radarr_name_change
      changed_when: true

    - name: Restart Sonarr container
      ansible.builtin.command:
        cmd: "docker restart sonarr"
      when: sonarr_name_change
      changed_when: true

    - name: Restart Readarr Audiobooks container
      ansible.builtin.command:
        cmd: "docker restart readarr_audiobooks"
      when: readarr_audiobooks_name_change
      changed_when: true

    - name: Restart Readarr Ebooks container
      ansible.builtin.command:
        cmd: "docker restart readarr_ebooks"
      when: readarr_ebooks_name_change
      changed_when: true

    - name: Wait for 15 seconds to allow the containers to start
      ansible.builtin.pause:
        seconds: 15

- name: MAM Cookies
  when: containers.pia_vpn and extras.mam.enabled
  tags: seedbox
  block:
    - name: Check if mam.cookies file exists (Extras MAM)
      ansible.builtin.stat:
        path: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/pia/persist/mam.cookies"
      register: mam_cookies
      tags:
        - seedbox

    - name: Wait for VPN container to be healthy (Extras MAM)
      community.docker.docker_container_info:
        name: pia_vpn
      register: pia_vpn_info
      until: pia_vpn_info.container.State.Health.Status == "healthy"
      retries: 30
      delay: 5
      tags:
        - seedbox
      when: not mam_cookies.stat.exists

    - name: Run command to generate MAM cookies (Extras MAM)
      community.docker.docker_container_exec:
        container: pia_vpn
        command: "curl -c /persist/mam.cookies -b 'mam_id={{ extras.mam.session_cookie }}' https://t.myanonamouse.net/json/dynamicSeedbox.php"
      tags:
        - seedbox
      when: not mam_cookies.stat.exists

- name: Regenerate Docker Compose File for Cleanuperr API Keys
  when: containers.cleanuparr
  tags: seedbox
  block:
    - name: Get Sonarr API Key
      when: containers.sonarr
      tags: seedbox
      ansible.builtin.include_tasks: getApiKey.yml
      vars:
        app_name: "sonarr"

    - name: Get Sonarr 2 API Key
      when: containers.sonarr_2
      tags: seedbox
      ansible.builtin.include_tasks: getApiKey.yml
      vars:
        app_name: "sonarr_2"

    - name: Get Radarr API Key
      when: containers.radarr
      tags: seedbox
      ansible.builtin.include_tasks: getApiKey.yml
      vars:
        app_name: "radarr"

    - name: Get Radarr 2 API Key
      when: containers.radarr_2
      tags: seedbox
      ansible.builtin.include_tasks: getApiKey.yml
      vars:
        app_name: "radarr_2"

    - name: Create docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "/home/{{ docker_user }}/dockers/{{ docker_directory_name }}/docker-compose.yml"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"

    - name: Create Seedbox Docker stack
      ansible.builtin.command:
        cmd: "docker compose -f /home/{{ docker_user }}/dockers/{{ docker_directory_name }}/docker-compose.yml up -d"
      changed_when: true
      tags: seedbox
