---
- name: Update and Upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
  tags:
    - packages
    - upgrade

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags:
    - packages
    