---
- name: Update and Upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
  tags:
    - packages
    - upgrade

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags:
    - packages

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
    enabled: true
  tags:
    - ssh

- name: Create mountpoint for UNRAID shares
  file:
    path: "/data"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - share

- name: Mount UNRAID shares
  mount:
    path: "/data/{{ item.mediaType }}"
    src: "{{ item.shareName }}"
    fstype: virtiofs
    state: mounted
  become: true
  loop: "{{ media_shares }}"
  tags:
    - share
