---
- name: Update and Upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
  tags:
    - packages
    - upgrade

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags:
    - packages

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
    enabled: true
  tags:
    - ssh

- name: Create mountpoint for UNRAID shares
  file:
    path: "/mnt/{{ unraid_mount_tag }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags:
    - share
- name: Mount UNRAID shares
  mount:
    path: "/mnt/{{ unraid_mount_tag }}"
    src: "{{ unraid_mount_tag }}"
    fstype: virtiofs
    state: mounted
  become: true
