---
- name: Check if docker command exists
  ansible.builtin.command:
    cmd: which docker
  register: docker_exists
  changed_when: false
  ignore_errors: true
  tags:
    - docker

- name: Set a fact to skip Docker installation if it exists
  ansible.builtin.set_fact:
    skip_docker_install: "{{ docker_exists.rc == 0 }}"
  tags:
    - docker

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true
  when: not skip_docker_install
  tags:
    - docker

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
  when: not skip_docker_install
  tags:
    - docker

- name: Remove any existing Docker repository
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: absent
  become: true
  tags:
    - docker

- name: Ensure the keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  when: not skip_docker_install

- name: Remove Docker GPG key if already exists
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: absent
  become: true
  when: not skip_docker_install
  tags:
    - docker

- name: Download Docker GPG key to the trusted.gpg.d directory
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  when: not skip_docker_install
  tags:
    - docker

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  when:
    - not skip_docker_install
  tags:
    - docker

- name: Update apt package index again after adding Docker repo
  ansible.builtin.apt:
    update_cache: true
  when: not skip_docker_install
  tags:
    - docker

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: not skip_docker_install
  tags:
    - docker

- name: Ensure Docker service is running and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: not skip_docker_install
  tags:
    - docker

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  when: not skip_docker_install
  tags:
    - docker

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  when: not skip_docker_install
  tags:
    - docker

- name: Create the dockers directory
  ansible.builtin.file:
    path: "/home/{{ docker_user }}/dockers"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"
  tags:
    - docker

- name: Setup SELinux
  tags: selinux
  when: shares.enable_selinux
  ansible.builtin.include_tasks:
    file: setupSELinux.yml
