---
- name: Check if docker command exists
  command: which docker
  register: docker_exists
  ignore_errors: true

- name: Set a fact to skip Docker installation if it exists
  set_fact:
    skip_docker_install: "{{ docker_exists.rc == 0 }}"

- name: Update apt package index
  apt:
    update_cache: yes
  when: not skip_docker_install
  tags:
    - docker

- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
  when: not skip_docker_install
  tags:
    - docker

- name: Remove any existing Docker repository
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: absent
  become: true
  tags:
    - docker

- name: Ensure the keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: not skip_docker_install

- name: Check if Docker GPG key already exists
  file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent
  when: not skip_docker_install
  tags:
    - docker

- name: Download Docker GPG key to the trusted.gpg.d directory
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  when: not skip_docker_install
  tags:
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: 
    - not skip_docker_install
  tags:
    - docker

- name: Update apt package index again after adding Docker repo
  apt:
    update_cache: yes
  when: not skip_docker_install
  tags:
    - docker

- name: Install Docker and related packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: not skip_docker_install
  tags:
    - docker

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  when: not skip_docker_install
  tags:
    - docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present
  when: not skip_docker_install
  tags:
    - docker

- name: Add user to the docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: not skip_docker_install
  tags:
    - docker

- name: Create the dockers directory
  file:
    path: "/home/{{ docker_user }}/dockers"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0755
  tags:
    - docker